### ISSUE TITLE
confused with line 166 in vundler.py

### ISSUE THREAD

**Issue by alongsang** [Esri/raster-tiles-compactcache#10]
curr_index[(row % BSZ ) * BSZ + col % BSZ] = curr_offset + (tsize << 40)
what does the (tsize << 40) mean?
i think it should be like this:
curr_index[(row % BSZ ) * BSZ + col % BSZ] = curr_offset

**Comment by lucianpls** [comment]
The code is correct.
tsize << 40 is the left bitwise shift of the tsize value by 40 positions, equivalent with tsize * (2 ** 40). It moves the tile size into the bits 40 to 63, as described in [Tile Index Record](https://github.com/Esri/raster-tiles-compactcache/blob/master/CompactCacheV2.md#tile-index-record) paragraph.

**Comment by alongsang** [comment]
Thanks for the update on the issue.
